"""add contract_audits table

Revision ID: 4f1b62198774
Revises: f641cdf036ea
Create Date: 2025-10-23 23:38:49.806232

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4f1b62198774'
down_revision = 'f641cdf036ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=42), nullable=False),
    sa.Column('network', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('ai_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contract_audits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contract_audits_address'), ['address'], unique=False)
        batch_op.create_index(batch_op.f('ix_contract_audits_network'), ['network'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract_audits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contract_audits_network'))
        batch_op.drop_index(batch_op.f('ix_contract_audits_address'))

    op.drop_table('contract_audits')
    # ### end Alembic commands ###
