"""add created_at y unique (address,network) a contract_abis

Revision ID: 86c6c8614af8
Revises: 4f1b62198774
Create Date: 2025-10-27 01:32:33.475240
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
# 👇 Agregá esta línea
from app.models.types import JSONBCompat

# revision identifiers, used by Alembic.
revision = '86c6c8614af8'
down_revision = '4f1b62198774'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract_abis', schema=None) as batch_op:
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=32),
               nullable=True)
        # 👇 cambiá esto
        batch_op.alter_column('abi',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=JSONBCompat(),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_contract_abis_created_at'))
        batch_op.drop_index(batch_op.f('ix_contract_abis_updated_at'))
        batch_op.drop_index(batch_op.f('ix_contract_abis_address'))
        batch_op.create_index('ix_contract_abis_address', ['address'], unique=False)
        batch_op.create_unique_constraint('uq_contract_abis_address_network', ['address', 'network'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract_abis', schema=None) as batch_op:
        batch_op.drop_constraint('uq_contract_abis_address_network', type_='unique')
        batch_op.drop_index('ix_contract_abis_address')
        batch_op.create_index(batch_op.f('ix_contract_abis_address'), ['address'], unique=True)
        batch_op.create_index(batch_op.f('ix_contract_abis_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_contract_abis_created_at'), ['created_at'], unique=False)
        # 👇 y esto también
        batch_op.alter_column('abi',
               existing_type=JSONBCompat(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
        batch_op.alter_column('source',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###
