"""add contract_abis table

Revision ID: f641cdf036ea
Revises: 14598cab0a23
Create Date: 2025-10-22 22:31:08.043458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f641cdf036ea'
down_revision = '14598cab0a23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_abis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=42), nullable=False),
    sa.Column('network', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('abi', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contract_abis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contract_abis_address'), ['address'], unique=True)
        batch_op.create_index(batch_op.f('ix_contract_abis_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_contract_abis_network'), ['network'], unique=False)
        batch_op.create_index(batch_op.f('ix_contract_abis_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract_abis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contract_abis_updated_at'))
        batch_op.drop_index(batch_op.f('ix_contract_abis_network'))
        batch_op.drop_index(batch_op.f('ix_contract_abis_created_at'))
        batch_op.drop_index(batch_op.f('ix_contract_abis_address'))

    op.drop_table('contract_abis')
    # ### end Alembic commands ###
